version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - username=python
      - password=123
      - host=10.10.10.29
      - port=27017
      - data_db=infra
      - auth_db=admin
      - collection_name=test
    volumes:
      - ./:/app
    command: python app.py
  mongo:
        image: mongo
        restart: unless-stopped
        ports:
          - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
  api:
    image: ghvinerias/py_api:1
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_USERNAME=python
      - MONGODB_PASSWORD=123
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE_NAME=infra
    volumes:
      - ./app.py:/app/app.py
  ubutnu:
    image: ubuntu
    entrypoint: ["bash"]