version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - username=python
      - password=123
      - host=10.10.10.29
      - port=27017
      - data_db=infra
      - auth_db=admin
      - collection_name=test
    volumes:
      - ./:/app
    command: python app.py
  mongo:
        image: mongo
        restart: unless-stopped
        ports:
          - "27017:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example